/**
 * Supabase Storage setup (Dashboard → Storage):
 * - Create a bucket named `reports`.
 * - Set the bucket to public (or add a storage policy allowing public read)
 *   so `getPublicUrl()` works for admin "Download PDF" links.
 * - Upload path used by the API: `reports/[YYYY-MM].pdf` (see reports/generate).
 */

import { DEFAULT_MONTHLY_RATE } from "@/lib/constants";
import type { ReportData } from "@/lib/types";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

const MARGIN = 50;
const PAGE_W = 595;
const PAGE_H = 842;
const BLACK = rgb(0.1, 0.1, 0.12);
const GRAY = rgb(0.45, 0.45, 0.45);

function formatCedis(n: number) {
  return `GHS ${n.toFixed(2)}`;
}

function monthTitle(d: Date) {
  return d.toLocaleString("en-US", { month: "long", year: "numeric" });
}

export async function generatePDF(reportData: ReportData): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);

  let page = doc.addPage([PAGE_W, PAGE_H]);
  let y = PAGE_H - MARGIN;

  const line = (spacing = 14) => {
    y -= spacing;
    if (y < MARGIN + 72) {
      page = doc.addPage([PAGE_W, PAGE_H]);
      y = PAGE_H - MARGIN;
    }
  };

  const text = (
    t: string,
    opts: { bold?: boolean; size?: number; color?: ReturnType<typeof rgb> } = {}
  ) => {
    const size = opts.size ?? 11;
    const f = opts.bold ? fontBold : font;
    const color = opts.color ?? BLACK;
    page.drawText(t, { x: MARGIN, y, size, font: f, color });
    line(size + 4);
  };

  const hr = () => {
    line(8);
    page.drawLine({
      start: { x: MARGIN, y },
      end: { x: PAGE_W - MARGIN, y },
      thickness: 0.5,
      color: rgb(0.8, 0.8, 0.8),
    });
    line(16);
  };

  text("KPAI FAMILY CONTRIBUTIONS", { bold: true, size: 18 });
  line(4);
  text(`Monthly Report — ${monthTitle(reportData.month)}`, { size: 13 });
  text(
    `Generated: ${reportData.generatedAt.toLocaleString("en-GB", {
      dateStyle: "medium",
      timeStyle: "short",
    })}`,
    { size: 10, color: GRAY }
  );
  hr();

  const paidList = reportData.members.filter((m) => m.paidThisMonth);
  const memberCount = reportData.members.length;

  text("Summary", { bold: true, size: 12 });
  text(`Total Collected This Month: ${formatCedis(reportData.totalCollectedThisMonth)}`);
  text(`Total Collected All Time: ${formatCedis(reportData.totalCollectedAllTime)}`);
  text(`Total Outstanding: ${formatCedis(reportData.totalOutstanding)}`);
  text(`Members Paid This Month: ${paidList.length} of ${memberCount}`);
  hr();

  text("MEMBERS WHO PAID THIS MONTH", { bold: true, size: 12 });
  line(6);
  text("Name | Amount Paid | Status", { bold: true, size: 9, color: GRAY });
  for (const m of paidList) {
    text(
      `✓ ${m.displayName}  |  ${formatCedis(m.amountPaidThisMonth)}  |  ${m.status}`,
      { size: 10 }
    );
  }
  if (paidList.length === 0) {
    text("— None —", { size: 10, color: GRAY });
  }
  line(12);
  hr();

  const unpaid = reportData.members
    .filter((m) => !m.paidThisMonth && m.balance > 0.01)
    .sort((a, b) => b.balance - a.balance);

  text("MEMBERS YET TO PAY", { bold: true, size: 12 });
  line(6);
  text("Name | Amount Behind | Months Behind", { bold: true, size: 9, color: GRAY });
  for (const m of unpaid) {
    const monthsBehind = Math.max(
      1,
      Math.ceil(m.balance / DEFAULT_MONTHLY_RATE)
    );
    text(
      `${m.displayName}  |  ${formatCedis(m.balance)}  |  ${monthsBehind}`,
      { size: 10 }
    );
  }
  if (unpaid.length === 0) {
    text("— None in this category —", { size: 10, color: GRAY });
  }

  line(24);
  text("Generated by Kpai Family Contributions Tracker", {
    size: 9,
    color: GRAY,
  });
  text("Powered by Cimons Technologies", { size: 9, color: GRAY });

  return doc.save();
}
